<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lucene.Net" Version="4.8.0-beta00018" />
    <PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta00018" />
    <PackageReference Include="Lucene.Net.Highlighter" Version="4.8.0-beta00018" />
    <PackageReference Include="Lucene.Net.Queries" Version="4.8.0-beta00018" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
    <PackageReference Include="SharpCompress" Version="0.50.0" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="10.0.10" />
    <PackageReference Include="System.Threading.Channels" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArchiveIndexer.Core\ArchiveIndexer.Core.csproj" />
  </ItemGroup>

</Project>
